openapi: "3.0.0"
info:
  title: Shopping API
  version: "1.0"
components:
  schemas:
    product:
      type: object
      description: A product
      required:
        - reference
        - name
        - price
        - supplier
      properties:
        reference:
          description: |
              Unique ID identifying
              a product
          type: string
        name:
          type: string
        price:
          description: Price in USD
          type: number
        description:
          type: string
        supplier:
          type: object
          description: Product's supplier
          required:
           - reference
           - name
          properties:
            reference:
              type: string
            name:
              type: string
  parameters:
    productId:
      name: productId
      in: path
      required: true
      description: Product's reference
      schema:
        type: string
           


paths: 
  /products:
    description: The products catalog
    get:
      summary: Search for products
      description: |
        Search for products in catalog
        using a free query parameter
      responses:
        "200":
          description: Products matching free query
          content:
            application/json:
              schema:
                type: array
                description: Array of products
                items:
                  $ref: "#/components/schemas/product"
                  

      parameters:
        - name: free-query
          description: |
            A product's name, reference, or
            partial description
          in: query
          required: false
          schema:
            type: string              
               
    post:
      summary: Add product
      description: |
        Add product (described in product info
        parameter) to catalog
      responses:
        "200":
          description: |
            Product added to catalog
          content:
            application/json:
              schema:
                required:
                  - name
                  - price
                  - supplierReference
                properties:
                  name:
                    type: string
                    example: "test name"
                  price:
                    type: number
                  description:
                    type: string
                  supplierReference:
                    type: string
                $ref: "#/components/schemas/product"

  /products/{productId}:
    description: A product
    parameters:
        - $ref: "#/components/parameters/productId"
    delete:
      summary: Delete a product
      responses:
        "200":
          description: |
            Product added to catalog
    put:
      responses:
        "200":
          description: |
            Product added to catalog
    patch:
      responses:
          "200":
            description: |
              Product added to catalog
