openapi: 3.0.3
info:
  title: Login API
  version: v1
  description: |-
    An API for login to platform.
tags:
  - name: Users
    description: Users and authentication.

servers:
  - url: https://fe-api.enres.co/api/v1
paths:                     
  /auth/login:
    post:
      tags:
        - Users
      description: Login to platform.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  landing_page:
                    type: string
                    example: "/overview"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: object
                    properties:
                      message: 
                        type: string
                        example: "Email does not exist."  
                      status_code:
                        type: number
                        example: "400"  